#!/usr/bin/env ruby

require 'json'

CACHE_DIR = ENV['ICHNO_DIR'] || 'tmp/cache/ichno'
CACHE_PATH = "#{CACHE_DIR}/manifest.json"

def parse_ichno(path)
  json = JSON.parse(File.read(path))
  json_proc = {}
  json.each do |data|
    id = "#{data['pid']}_#{data['tid']}"
    json_proc[id] ||= []
    json_proc[id] << data
  end

  json.each do |data|
    id = "#{data['pid']}_#{data['tid']}"
    json_proc[id] ||= []
    json_proc[id] << data
  end

  caches = {}
  json_proc.each do |id, jsn|
    tmp = []
    jsn.each do |data|
      next if data['path'].include?('ichno.cache.json')
      next if data['path'].match?('\/cache\/')
      next if data['path'].match?('\/tmp\/')
      next if data['path'].match?('\/log\/')
      if data['path'].match?(/.*?_spec.rb/)
        if tmp.size.nonzero?
          caches[tmp[0]['path']] = tmp
          tmp = []
        end
        tmp << data
        next
      end

      if tmp.size.nonzero?
        tmp << data
      end
    end
    caches[tmp[0]['path']] = tmp if tmp.size.nonzero?
  end

  caches
end

def parse_rspec(path)
  ret = {}

  rspec_result = JSON.parse(File.read(path))
  examples = rspec_result['examples'].select{|e|e['status'] == 'failed'}
  return ret if examples.count.zero?
  examples.each do |example|
    path = example['id'].split('[').first
    ret[File.absolute_path(path)] = true
  end

  ret
end

ichno_caches = parse_ichno(ARGV[0])
rspec_caches = parse_rspec(ARGV[1])

cache = {}
cache ||= JSON.parse(File.read(CACHE_PATH)) if File.exist?(CACHE_PATH)
cache['version'] = RUBY_VERSION
ichno_caches.each do |path, data|
  tmp = {}
  tmp['data'] = data
  tmp['failed'] = rspec_caches[path] ? true : false
  cache[path] = tmp
end
File.write(CACHE_PATH, JSON.dump(cache))
