#!/usr/bin/env ruby

require 'json'
require 'pathname'

CACHE_DIR = ENV['ICHNO_DIR'] || 'tmp/cache/ichno'
CACHE_PATH = "#{CACHE_DIR}/manifest.json"

def elf_binary?(path)
  return false if File.directory?(path)

  header = File.open(path, 'r').read(4)
  header == "\x7fELF"
end

def parse_ichno_global(path)
  json = JSON.parse(File.read(path))
  caches = {}

  skip_paths = ['/etc', '/lib', '/cache/', '/log/', '.bundle']
  json.each do |data|
    next if skip_paths.detect{|pth|data['path'].include?(pth)}
    next if data['path'].include?('/usr') && !data['path'].include?('/usr/local')
    next unless File.exist?(data['path'])
    next if File.lstat(data['path']).symlink?
    next if elf_binary?(data['path'])
    next if data['path'].include?(Pathname(ENV['HOME']).join('.local').to_s)
    next if data['path'].include?(Pathname(ENV['HOME']).join('.cache').to_s)
    next if data['path'].include?('.log')
    break if data['path'].include?('_spec.rb')

    caches[data['path']] = data
  end

  caches
end

def parse_ichno_spec(path)
  json = JSON.parse(File.read(path))
  json_proc = {}
  json.each do |data|
    id = "#{data['pid']}_#{data['tid']}"
    json_proc[id] ||= []
    json_proc[id] << data
  end

  json.each do |data|
    id = "#{data['pid']}_#{data['tid']}"
    json_proc[id] ||= []
    json_proc[id] << data
  end

  caches = {}
  json_proc.each do |id, jsn|
    tmp = []
    jsn.each do |data|
      next if data['path'].include?('ichno.cache.json')
      next if data['path'].match?('\/cache\/')
      next if data['path'].match?('\/tmp\/')
      next if data['path'].match?('\/log\/')
      if data['path'].match?(/.*?_spec.rb/)
        if tmp.size.nonzero?
          caches[tmp[0]['path']] = tmp
          tmp = []
        end
        tmp << data
        next
      end

      if tmp.size.nonzero?
        tmp << data
      end
    end
    caches[tmp[0]['path']] = tmp if tmp.size.nonzero?
  end

  caches
end

def parse_rspec(path)
  ret = {}

  rspec_result = JSON.parse(File.read(path))
  examples = rspec_result['examples'].select{|e|e['status'] == 'failed'}
  return ret if examples.count.zero?
  examples.each do |example|
    path = example['id'].split('[').first
    ret[File.absolute_path(path)] = true
  end

  ret
end

ichno_global_caches = parse_ichno_global(ARGV[0])
ichno_caches = parse_ichno_spec(ARGV[0])
rspec_caches = parse_rspec(ARGV[1])

cache = {}
cache ||= JSON.parse(File.read(CACHE_PATH)) if File.exist?(CACHE_PATH)
cache['version'] = RUBY_VERSION
cache['global'] = ichno_global_caches
ichno_caches.each do |path, data|
  tmp = {}
  tmp['data'] = data
  tmp['failed'] = rspec_caches[path] ? true : false
  cache[path] = tmp
end
File.write(CACHE_PATH, JSON.dump(cache))
